spring:
  datasource:
    url: jdbc:mysql://localhost:3306/incidencias  # URL de la base de datos 'incidencia'
    username: root                              # Usuario 'root'
    password: root                              # Contraseña 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver  # Driver para MySQL

  jpa:
    hibernate:
      ddl-auto: update                 # Hibernate actualiza el esquema con la entidad 'Issue'
    show-sql: true                     # Mostrar consultas SQL en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Dialecto de Hibernate para MySQL
        format_sql: true               # Formatear las consultas SQL para mejor lectura

  # Configuración del pool de conexiones (opcional)
hikari:
      minimum-idle: 5                  # Conexiones mínimas inactivas en el pool
      maximum-pool-size: 20            # Número máximo de conexiones en el pool
      idle-timeout: 600000             # Tiempo antes de liberar una conexión inactiva (en ms)
      max-lifetime: 1800000            # Vida máxima de una conexión en el pool (en ms)
      connection-timeout: 30000        # Tiempo máximo de espera para obtener una conexión (en ms)

# Configuración de servidor opcional (puedes ajustar esto según tus necesidades)
server:
  port: 8080                           # Puerto del servidor Spring Boot
  error:
    whitelabel:
      enabled: false                   # Desactivar la página de error por defecto


